[workspace]
members = [
    "opentelemetry-*",
    "examples/*",
]
exclude = [
    "opentelemetry-dynatrace",
]
resolver = "2"

[profile.bench]
# https://doc.rust-lang.org/cargo/reference/profiles.html#bench
# See function names in profiling reports.
# 2/true is too much, 0 is not enough, 1 is just right for back traces
debug = 1

[workspace.dependencies]
opentelemetry = "0.23"
opentelemetry-appender-tracing = "0.4"
opentelemetry-http = "0.12"
opentelemetry-proto = { version = "0.6", default-features = false }
opentelemetry_sdk = { version = "0.23", default-features = false }
opentelemetry-stdout = "0.4"
opentelemetry-semantic-conventions = "0.15"

[patch.crates-io]
# FIXME: Drop the patches below when https://github.com/open-telemetry/opentelemetry-rust/pull/1674 is merged.
opentelemetry = { git = "https://github.com/grafbase/opentelemetry-rust", rev = "9d6216de8488aab8837f74673fe11037c4d99bc2" } # http-v1-as-any-rebased
opentelemetry-proto = { git = "https://github.com/grafbase/opentelemetry-rust", rev = "9d6216de8488aab8837f74673fe11037c4d99bc2" } # http-v1-as-any-rebased
opentelemetry_sdk = { git = "https://github.com/grafbase/opentelemetry-rust", rev = "9d6216de8488aab8837f74673fe11037c4d99bc2" } # http-v1-as-any-rebased
opentelemetry-http = { git = "https://github.com/grafbase/opentelemetry-rust", rev = "9d6216de8488aab8837f74673fe11037c4d99bc2" } # http-v1-as-any-rebased
